name: lazy_indexed_stack_plus
description: "The ultimate enhanced IndexedStack with lazy loading, preloading, and state preservation made easy for optimized Flutter apps."
version: 0.0.3
homepage: https://github.com/rahulrao24/lazy_indexed_stack_plus
repository: https://github.com/rahulrao24/lazy_indexed_stack_plus
issue_tracker: https://github.com/rahulrao24/lazy_indexed_stack_plus/issues
documentation: https://github.com/rahulrao24/lazy_indexed_stack_plus?tab=readme-ov-file#usage
topics:
  - lazy-loading
  - widget
  - state-management
  - performance
  - indexed-stack

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
